program: train.py
command:
  - ${interpreter}
  - ${program}
  - ${args_no_boolean_flags}
method: grid
metric:
  name: max_accuracy_validation
  goal: maximize
parameters:
  seed:
    values: [ 30 ]
  cuda:
    values: [ true ]
  cuda_id:
    values: [ 0 ]
  batch_size:
    values: [ 128 ]
  epoch:
    values: [0]
  max_epochs:
    values: [ 10 ]
  lr_decay:
    values: [ true ] # false
  backbone:
    values: [ "alex"]
  model:
    values: ["rsscnn" ]
  comparisons:
    values: ["data/comparisons_synthetic_frac0.001.p",
             "data/comparisons_synthetic_frac0.005.p",
             "data/comparisons_synthetic_frac0.010.p",
             "data/comparisons_synthetic_frac0.050.p",
             "data/comparisons_synthetic_frac0.100.p",
             "data/comparisons_synthetic_frac0.150.p",
             "data/comparisons_synthetic_frac0.200.p",
             "data/comparisons_synthetic_frac0.250.p",
             "data/comparisons_synthetic_frac0.300.p",
             "data/comparisons_synthetic_frac0.400.p",
             "data/comparisons_synthetic_frac0.500.p",
             "data/comparisons_synthetic_frac0.600.p",
             "data/comparisons_synthetic_frac0.700.p",
             "data/comparisons_synthetic_frac0.800.p",
             "data/comparisons_synthetic_frac0.900.p",
             "data/comparisons_synthetic_frac1.000.p",] # ../comparisons_df.pickle
  dataset:
    values: ["/home/mncosta/data/images/"]
  resume:
    values: [false]
  resume_realimages:
    values: [ false ]
  finetune:
    values: [false]
  model_dir:
    values: ["models/"]
  ties:
    values: [ true ]
  rank_w:
    values: [ 1 ]
  ties_w:
    values: [ 1 ]
  ranking_margin:
    values: [ 1 ]
  ranking_margin_ties:
    values: [ 0 ]
  log_console:
    values: [ true ]
  log_wandb:
    values: [ true ]
  full_accuracy:
    values: [ true ]

