program: train.py
command:
  - ${interpreter}
  - ${program}
  - ${args_no_boolean_flags}
method: grid
metric:
  name: max_accuracy_validation
  goal: maximize
parameters:
  seed:
    values: [ 30 ]
  cuda:
    values: [ true ]
  cuda_id:
    values: [ 0 ]
  batch_size:
    values: [ 128 ]
  epoch:
    values: [0]
  max_epochs:
    values: [ 20 ]
  lr_decay:
    values: [ true ] # false
  backbone:
    values: [ "alex"]
  model:
    values: ["rsscnn" ]
  comparisons:
    values: ["data/comparisons_synthetic_pc100.01.p","data/comparisons_synthetic_pc12.01.p","data/comparisons_synthetic_pc15.01.p","data/comparisons_synthetic_pc1.50.p","data/comparisons_synthetic_pc20.00.p","data/comparisons_synthetic_pc2.00.p","data/comparisons_synthetic_pc30.00.p","data/comparisons_synthetic_pc3.01.p","data/comparisons_synthetic_pc50.00.p","data/comparisons_synthetic_pc5.00.p","data/comparisons_synthetic_pc8.01.p"] # ../comparisons_df.pickle
  dataset:
    values: ["/home/mncosta/data/images/"]
  resume:
    values: [false]
  resume_realimages:
    values: [ false ]
  finetune:
    values: [false]
  model_dir:
    values: ["models/"]
  ties:
    values: [ true ]
  rank_w:
    values: [ 1 ]
  ties_w:
    values: [ 1 ]
  ranking_margin:
    values: [ 1 ]
  ranking_margin_ties:
    values: [ 0 ]
  log_console:
    values: [ true ]
  log_wandb:
    values: [ true ]
  full_accuracy:
    values: [ true ]

